/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mainPack_Main */

#ifndef _Included_mainPack_Main
#define _Included_mainPack_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mainPack_Main
 * Method:    nativeParallelMultiplyMatrixWithVector
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_mainPack_Main_nativeParallelMultiplyMatrixWithVector
  (JNIEnv *, jobject, jint);

/*
 * Class:     mainPack_Main
 * Method:    nativeSequentialMultiplyMatrixWithVector
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_mainPack_Main_nativeSequentialMultiplyMatrixWithVector
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
